<a href="https://colab.research.google.com/github/danaderp/DeepLearningTutorials/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [0]:
# Create a Torch tensor
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
#Transposing a Tensor in two ways
# Transpose
t.t()

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [0]:
# Transpose (via permute)
t.permute(-1,0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [0]:
#Note that neither result in a change to the original. Transposing won't change the shape

In [0]:
#Reshaping
# Reshape via view
t.view(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [0]:
# View again...
t.view(6,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

In [0]:
#Create a tensor and fill it with zeros (you can accomplish something similar with ones()):
t = torch.zeros(3, 3)
t

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [0]:
#Create a tensor with randoms pulled from the normal distribution:
t = torch.randn(3, 3)
t

tensor([[ 0.4867, -1.5692,  1.1211],
        [-0.2227, -0.5317,  1.1691],
        [-0.9875,  1.7269,  0.7609]])

In [0]:
# Some tensor info
print('Tensor shape:', t.shape)   # t.size() gives the same
print('Number of dimensions:', t.dim())
print('Tensor type:', t.type())   # there are other types

Tensor shape: torch.Size([3, 3])
Number of dimensions: 2
Tensor type: torch.FloatTensor


In [0]:
#You can slice PyTorch tensors the same way you slice ndarrays, which should be familiar to anyone who uses other Python structures:
# Slicing
t = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Every row, only the last column
print(t[:, -1])

# First 2 rows, all columns
print(t[:2, :])

# Lower right most corner
print(t[-1:, -1:])

tensor([3., 6., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[9.]])


### PyTorch Tensor To and From Numpy ndarray

You can easily create a tensors from an ndarray and vice versa. These operations are fast, since the data of both structures will share the same memory space, and so no copying is involved. This is obviously an efficient approach.

In [0]:
# ndarray to tensor
a = np.random.randn(3, 5)
t = torch.from_numpy(a)
print(a)
print(t)
print(type(a))
print(type(t))

[[ 0.68242997 -0.93065963  0.10525168 -1.05315403  0.52094378]
 [ 1.25888634 -0.18278963 -1.65849613  0.11423179  0.86654418]
 [-0.18580976  2.35531309  0.35603849  0.64255241  0.8650785 ]]
tensor([[ 0.6824, -0.9307,  0.1053, -1.0532,  0.5209],
        [ 1.2589, -0.1828, -1.6585,  0.1142,  0.8665],
        [-0.1858,  2.3553,  0.3560,  0.6426,  0.8651]], dtype=torch.float64)
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [0]:
# tensor to ndarray
t = torch.randn(3, 5)
a = t.numpy()
print(t)
print(a)
print(type(t))
print(type(a))

tensor([[ 1.0929,  0.3266, -1.0328, -1.1205, -0.3290],
        [ 0.2044, -0.5399, -2.0760,  0.1913,  1.4445],
        [ 1.7322, -1.1109,  1.0278, -1.4219, -0.6022]])
[[ 1.09295     0.32660463 -1.0328249  -1.1204923  -0.32901803]
 [ 0.2043658  -0.53986263 -2.076049    0.19131471  1.4444665 ]
 [ 1.7322282  -1.1109455   1.027835   -1.4218614  -0.6021822 ]]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### Basic Tensor Operations

Here are a few tensor operations, which you can compare with Numpy implementations for fun. First up is the cross product:

In [0]:
# Compute cross product
t1 = torch.randn(4, 3)
t2 = torch.randn(4, 3)
t1.cross(t2)

tensor([[ 2.1078,  0.8798,  0.9369],
        [ 2.3220, -0.6878,  1.5205],
        [-0.9195, -2.8440, -3.7967],
        [-0.0437, -0.3287,  0.8895]])

In [0]:
# Compute matrix product
t = (torch.Tensor([[2, 4], [5, 10]]).mm(torch.Tensor([[10], [20]])))
t

tensor([[100.],
        [250.]])

In [0]:
# Elementwise multiplication
t = torch.Tensor([[1, 2], [3, 4]])
t.mul(t)

tensor([[ 1.,  4.],
        [ 9., 16.]])

### A Word About GPUs

PyTorch tensors have inherent GPU support. Specifying to use the GPU memory and CUDA cores for storing and performing tensor calculations is easy; the cuda package can help determine whether GPUs are available, and the package's cuda() method assigns a tensor to the GPU.

In [0]:
# Is CUDA GPU available?
torch.cuda.is_available()


False

In [0]:

# How many CUDA devices?
torch.cuda.is_available()


False

In [0]:

# Move to GPU
t.cuda()